[package]
name = "logic-book-sl-language"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.11"
pest_derive = "2.7.11"
itertools = "0.13.0"
generic-array = "1.1.0"
strum_macros = "0.26.4"
